name: PR Checks

on:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Version      
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.12.0'
          
      - name: Restore Packages
        run: dotnet restore src\LicenseClearingTool.sln
        
      - name: Build
        run: dotnet build src\LicenseClearingTool.sln

  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Commit Lint
        uses: wagoid/commitlint-github-action@v6
        with:
          failOnErrors: false
          helpURL: "https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional"

  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR Title Follows Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-description-check:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR Has a Description
        run: |
          if [ -z "${{ github.event.pull_request.body }}" ]; then
            echo "::error::Pull request must have a description."
            exit 1  # Fails the check
          fi
